# Generated by Django 5.0.7 on 2024-07-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
